config/routes.rb
Catarogu::Application.routes.draw do
  get "recommend", to: 'catarogu#recommend', as: :recommend

  root :to => 'catarogu#index'

  resources :shops

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :image, :image_cache, :recommend
  mount_uploader :image, ProductImageUploader

  validates_presence_of :name, :description
  validates_numericality_of :price, only_integer: true, greater_than_or_equal_to: 0
  validates_uniqueness_of :name
  validate :price_must_be_a_multiple_of_hundreds

  scope :recommend, where(recommend: true)

  private
  def price_must_be_a_multiple_of_hundreds
    unless price % 100 == 0
      errors.add :price, "must be a multiple of hundreds"
    end
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :description, :lines_summary, :name, :image, :image_cache
  mount_uploader :image, ShopImageUploader

  validates_presence_of :name, :description, :lines_summary
  validates_uniqueness_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/catarogu_controller.rb
class CataroguController < ApplicationController
  def index
    @products = Product.all
  end

  def recommend
    @products = Product.recommend
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catarogu_helper.rb
module CataroguHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/catarogu/index.html.haml
%h1 商品カタログ
- @products.each do |product|
  %h2
    = product.name
  %p
    = product.display_price
  %p
    = product.display_image
  %p
    = product.display_description

app/views/catarogu/recommend.html.haml
%h1 おすすめ
- @products.each do |product|
  %h2
    = product.name
  %p
    = product.display_price
  %p
    = product.display_image
  %p
    = product.display_description

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Catarogu
    %meta(charset='utf-8')
    %meta{:name => 'viewport', :content => 'width=device-width'}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        .brand
          = link_to 'Catarogu', root_path
        %ul.nav
          %li= link_to 'Recommend', recommend_path
  .container
    .content
      = yield
    %footer
      %p &copy; Company 2012

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :image
    = image_tag(@product.image_url) if @product.image?
    = f.file_field :image
    = f.hidden_field :image_cache
  .field
    = f.label :recommend
    = f.check_box :recommend

  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Name
    %th Description
    %th Price
    %th Image
    %th Recommend
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.name
      %td= product.display_description
      %td= product.price
      %td= product.display_image
      %td= product.recommend
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p.name
  %b Name:
  = @product.name
.description
  %p
    %b Description:
    = @product.display_description
%p.price
  %b Price:
  = @product.price
%p.image
  %b Image:
  = @product.display_image
%p.recommend
  %b Recommend:
  = @product.recommend

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

app/views/shops/_form.html.haml
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      %ul
        - @shop.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :lines_summary
    = f.text_field :lines_summary
  .field
    = f.label :image
    = image_tag(@shop.image_url) if @shop.image?
    = f.file_field :image
    = f.hidden_field :image_cache
  .actions
    = f.submit 'Save'

app/views/shops/edit.html.haml
%h1 Editing shop

= render 'form'

= link_to 'Show', @shop
\|
= link_to 'Back', shops_path

app/views/shops/index.html.haml
%h1 Listing shops

%table
  %tr
    %th Name
    %th Description
    %th Lines summary
    %th Image
    %th
    %th
    %th

  - @shops.each do |shop|
    %tr
      %td= shop.name
      %td= simple_format(shop.description)
      %td= simple_format(shop.lines_summary)
      %td= image_tag(shop.image_url) if shop.image?
      %td= link_to 'Show', shop
      %td= link_to 'Edit', edit_shop_path(shop)
      %td= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Shop', new_shop_path

app/views/shops/new.html.haml
%h1 New shop

= render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.haml
%p#notice= notice

%p.name
  %b Name:
  = @shop.name
.description
  %p
    %b Description:
    = simple_format(@shop.description)
.lines_summary
  %b Lines summary:
  = simple_format(@shop.lines_summary)
%p.image
  %b Image:
  = image_tag(@shop.image_url) if @shop.image?

= link_to 'Edit', edit_shop_path(@shop)
\|
= link_to 'Back', shops_path